spring:
  cloud:
    nacos:
      discovery:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
      config:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
    sentinel:
      transport:
        # port: 9002 # 应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer,可不提供，默认为 8719，若端口冲突会自动向下探测可用的端口。
        dashboard: 127.0.0.1:8849 # Sentinel 控制台地址
      datasource: # 动态数据源支持
        ds1: # ds1, ds2, ds3, ds4 是ReadableDataSource的名字，可随意编写。后面的 file ，zk ，nacos , apollo 就是对应具体的数据源，它们后面的配置就是这些具体数据源各自的配置。
          nacos:
            namespace: ${spring.cloud.nacos.config.namespace}
#  redis:
#    database: 0
#    port: 6379
#    host: 172.16.3.184
#    password: redis123
