spring:
  cloud:
    nacos:
      discovery:
        namespace: 1f966ded-f369-4ec8-ac84-2fe03d3710b4
      config:
        namespace: 1f966ded-f369-4ec8-ac84-2fe03d3710b4
  redis:
    database: 0
    port: 6379
    host: 172.16.3.184
    password: redis123
